### ISSUE TITLE
Go sucks and this project should be deleted because of this

### ISSUE THREAD

**Issue by fucksophie** [LordOfTrident/snash#1]
fuck go!@!!!!!!!!!!! and i hate go because it's made by leftist media and go devs are actually nazis
delete this blasphemy fuck go it's absolutely trash and fuck go and it sucks
fuck go !! !anti go alliance i hate go i hate go i hate go fuck GOO!!
leftist media keeps feeding u GO IS SUCKY!!! FUCK GO FUCK GO
fuck GO !! leftist media leftist media !! FUCK GO IT IS BRAINWASHING

THANK YOU FOR COMING TO MY TED TALK

**Comment by MESYETI** [comment]
i think this project should be rewritten in D

**Comment by MESYETI** [comment]
who agrees

**Comment by LordOfTrident** [comment]
i dont agree lol

**Comment by fucksophie** [comment]
> i dont agree lol

Shut up lord of penis go lover

**Comment by MESYETI** [comment]
> i dont agree lol

woah you can't be informal what if someone starts hating you and starts thinking you are a badword hole

**Comment by fucksophie** [comment]
> who agrees

Yes i agree d is way better than go

**Comment by MESYETI** [comment]
> > who agrees
> 
> Yes i agree d is way better than go

so true
